In [45]:
import numpy as np

row = 6
col = 7

# Define the matrix as a global variable
matrix = np.zeros((row, col))

def create_board():
    global matrix  
    matrix = np.zeros((row, col))
    return matrix

def drop_piece(col, piece):
    global matrix  
    for i in range(row-1, -1, -1):
        if matrix[i][col] == 0:
            matrix[i][col] = piece
            break

def game_start():
    global matrix  
    matrix = create_board()
    return matrix

def load_move(move):
    global matrix
    move = move_convert(move)
    for player, move in enumerate(move):
        if player == 1:
            matrix = drop_piece(move[0], 1)
        else:
            matrix = drop_piece(move[0], 2)    


def move_convert (move):
    if move.count(0)%2 == 0:
        return move.reshape(2,)
    else:
        move.append(0)
        return move.reshape(2,)



In [49]:
import numpy as np

row = 6
col = 7


matrix = np.zeros((row, col))

def create_board():
    global matrix  
    matrix = np.zeros((row, col))
    return matrix

def drop_piece(col, piece):
    global matrix  
    for i in range(row-1, -1, -1):
        if matrix[i][col-1] == 0:  
            matrix[i][col-1] = piece
            return True
    return False  

def game_start():
    global matrix  
    matrix = create_board()
    return matrix

def load_moves(moves):
    global matrix
    player = 1  
    for move in moves:
        player = 2 if player == 1 else 1  

game_start()  
moves = [1, 2, 3, 4, 3, 3, 3, 3, 4]  
load_moves(moves)
print(matrix)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [54]:
import numpy as np

row = 6
col = 7

matrix = np.zeros((row, col))

def create_board():
    global matrix  
    matrix = np.zeros((row, col))
    return matrix

def drop_piece(col, piece):
    global matrix  
    for i in range(row-1, -1, -1):
        if matrix[i][col-1] == 0:  
            matrix[i][col-1] = piece
            return True
    return False  

def game_start():
    global matrix  
    matrix = create_board()
    return matrix

def load_moves(moves):
    global matrix
    player = 1  
    for move in moves:
        if move < 1 or move > col:  
            print(f"Move {move} is out of bounds.")
            continue
        if not drop_piece(move, player):
            print(f"Column {move} is full.")
            continue
        player = 2 if player == 1 else 1  
        

game_start()  
moves = [1, 2, 3, 4, 3, 3, 3, 3, 4]  
load_moves(moves)

In [55]:
matrix

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0.],
       [1., 2., 1., 2., 0., 0., 0.]])